# Generated by Django 5.2.4 on 2025-07-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_alter_userprofile_role_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view_books', 'Can view books'), ('can_add_books', 'Can add books'), ('can_change_books', 'Can change books'), ('can_delete_books', 'Can delete books'))},
        ),
    ]
